### ISSUE TITLE
"Unable to run script in this page" when trying to use the script

### ISSUE THREAD

**Issue by Dioxaz** [shirohana/chrome-pixiv-fanbox-helper#1]
Hello there. I just wanted to test this script out of curiosity on a Fanbox post (from an account which I'm an actual supporter of). Even though I think I allowed the script to work on fanbox URLs, I'm still greeted with that "Unable to run script in this page" message when I click on the extension button. I'm using Chrome 116.0.5845.97 on Windows 10 x64.

Did I forget something? Apologizes if I didn't read something or something trivial escaped my attention (I haven't seen yet any documentation and Googling obviously give no result, as the extension seems very niche).

**Comment by shirohana** [comment]
Hello Dioxaz san, thank you for your feedback ヾ(\*´ω｀\*)ノ

I've just fixed up this issue. Please download the new version (v0.1.1) and try again. Sorry for the inconvenience.

The reason is that the post urls of FANBOX has two formats:

(example)
1. https://www.fanbox.cc/@kanibiimu/posts/6541301
2. https://kanibiimu.fanbox.cc/posts/6541301

They are interoperable, but in `v0.1.0` we only support the first one.

Thank you for trying and feedback!

**Comment by Dioxaz** [comment]
Thank you for the quick reply. Yes, this version now indeed work. Thank you very much. This script will prove very useful.
